language: python
python:
  - "3.5"
  - "3.6"

env:
  global:
    - "PYTHONUSERBASE=.cache/"
  matrix:
    # - "MPI=mpich PY=3"
    - "MPI=openmpi PY=3"

os: linux
dist: trusty
sudo: required

git:
  depth: false

cache:
  pip: true
  apt: true
  directories:
    - .cache

branches:
  only:
    - master

before_install:
  - ./conf/install-mpi.sh $MPI
  - ./conf/install-blas.sh
  - python -m pip install cython
  - python$PY --version
  # - python -c "import numpy;print(numpy.__version__)"
  - if [[ "$MPI" == "mpich"   ]]; then mpichversion; fi
  - if [[ "$MPI" == "openmpi" ]]; then ompi_info;    fi

install:
  - python$PY -m pip install .
  - ./conf/git-clone-if-not-exist.sh https://github.com/scipy/scipy.git .cache/scipy
  - python$PY -m pip install -q --user .cache/scipy

before_script:
  - if [[ "$MPI" == "mpich" ]]; then P=2; else P=5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];  then P=2; fi

script:
  - mpiexec -n 1 python setup.py test -v
  - mpiexec -n $P python setup.py test -v
