language: python
python:
  - "3.5"
  - "3.6"

env:
  - "MPI=mpich PY=3"
  - "MPI=openmpi PY=3"

os: linux
dist: trusty
sudo: required

git:
  depth: 3

cache:
  - pip
  - apt

before_install:
  - ./conf/ci/travis-ci/install-mpi.sh $MPI
  # - python$PY -m pip install Cython
  - python$PY --version
  # - python$PY -m cython --version
  # - python$PY -c "import numpy;print(numpy.__version__)"
  - if [[ "$MPI" == "mpich"   ]]; then mpichversion; fi
  - if [[ "$MPI" == "openmpi" ]]; then ompi_info;    fi

install:
  - python$PY -m pip -vvv install .

before_script:
  - if [[ "$MPI" == "mpich" ]]; then P=2; else P=5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];  then P=2; fi

script:
  - mpiexec -n 1 python$PY setup.py test -v
  - mpiexec -n $P python$PY setup.py test -v
